In [10]:
import nn
import numpy as np 
import pandas as pd 
from matplotlib import pyplot as plt

In [11]:
data = pd.read_csv('train.csv')

In [12]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [ ]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

# validation set
data_dev = data[:1000].T 
Y_dev = data_dev[0] # extract labels
X_dev = data_dev[1:n] / 255.0  # normalize

# train set
data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n] / 255.0 

In [14]:
X_train[:, 0].shape

(784,)

In [39]:
W1, b1, W2, b2 = nn.gradient_descent(X_train, Y_train, 100, 0.8)

Iteration:  0
[4 8 6 ... 8 8 6] [0 0 9 ... 2 2 6]
Accuracy:  0.15241463414634146
Iteration:  10
[0 0 2 ... 3 2 0] [0 0 9 ... 2 2 6]
Accuracy:  0.4746341463414634
Iteration:  20
[0 0 9 ... 2 2 6] [0 0 9 ... 2 2 6]
Accuracy:  0.6148292682926829
Iteration:  30
[0 0 4 ... 2 2 6] [0 0 9 ... 2 2 6]
Accuracy:  0.6269756097560976
Iteration:  40
[0 0 9 ... 2 2 6] [0 0 9 ... 2 2 6]
Accuracy:  0.719609756097561
Iteration:  50
[0 0 9 ... 2 2 6] [0 0 9 ... 2 2 6]
Accuracy:  0.762390243902439
Iteration:  60
[0 0 9 ... 2 2 6] [0 0 9 ... 2 2 6]
Accuracy:  0.791
Iteration:  70
[0 0 9 ... 2 2 6] [0 0 9 ... 2 2 6]
Accuracy:  0.8015853658536586
Iteration:  80
[0 0 9 ... 2 2 6] [0 0 9 ... 2 2 6]
Accuracy:  0.8113170731707318
Iteration:  90
[0 0 9 ... 2 2 6] [0 0 9 ... 2 2 6]
Accuracy:  0.8439512195121951
